# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

from pathlib import Path
from typing import Annotated

from pydantic import Field

from aiperf.common.config.base_config import BaseConfig
from aiperf.common.config.cli_parameter import CLIParameter
from aiperf.common.config.config_defaults import OutputDefaults
from aiperf.common.config.groups import Groups


class OutputConfig(BaseConfig):
    """
    A configuration class for defining output related settings.
    """

    _CLI_GROUP = Groups.OUTPUT

    artifact_directory: Annotated[
        Path,
        Field(
            description="The directory to store all the (output) artifacts generated by AIPerf.",
        ),
        CLIParameter(
            name=(
                "--output-artifact-dir",
                "--artifact-dir",  # GenAI-Perf
            ),
            group=_CLI_GROUP,
        ),
    ] = OutputDefaults.ARTIFACT_DIRECTORY

    profile_export_file: Annotated[
        Path | None,
        Field(
            description="Base name for profile export files (without extension). "
            "If not specified, will be auto-generated from model name, endpoint type, and concurrency.",
        ),
        CLIParameter(
            name=(
                "--profile-export-file",
            ),
            group=_CLI_GROUP,
        ),
    ] = OutputDefaults.PROFILE_EXPORT_FILE
