# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
"""
AIPerf Plugin System
"""

########################################################################
## 🚩                     mkinit flags                             🚩 ##
########################################################################
__ignore__ = []
# Make the list of submodules empty to avoid recursively adding
# everything from those modules into the top-level here.
__submodules__ = []
########################################################################
## ⚠️       This file is auto-generated by `make init-files`       ⚠️ ##
## ⚠️                Do not edit below this line                   ⚠️ ##
########################################################################
__all__ = []
